# Generated by Django 5.1.1 on 2025-08-09 07:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        ("companies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True,
                        help_text="Title of the job position.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Full description of the job responsibilities and requirements."
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full-time"),
                            ("part_time", "Part-time"),
                            ("contract", "Contract"),
                            ("temporary", "Temporary"),
                            ("internship", "Internship"),
                        ],
                        default="full_time",
                        help_text="Type of employment (e.g., full-time, part-time).",
                        max_length=20,
                    ),
                ),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum annual salary for the position.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum annual salary for the position.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="KSh",
                        help_text="Currency for the salary (e.g., USD, KSh).",
                        max_length=10,
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("entry", "Entry Level"),
                            ("junior", "Junior"),
                            ("mid", "Mid Level"),
                            ("senior", "Senior Level"),
                            ("director", "Director"),
                            ("executive", "Executive"),
                        ],
                        default="mid",
                        help_text="Required experience level for the job.",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates if the job listing is currently active and visible.",
                    ),
                ),
                (
                    "application_deadline",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deadline for submitting applications.",
                        null=True,
                    ),
                ),
                (
                    "external_application_url",
                    models.URLField(
                        blank=True,
                        help_text="URL for external application portal, if applicable.",
                        max_length=2000,
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Entry"),
                            ("scraped", "Web Scraped"),
                        ],
                        default="manual",
                        help_text="Origin of the job listing (manual entry or web scraped).",
                        max_length=10,
                    ),
                ),
                (
                    "original_url",
                    models.URLField(
                        blank=True,
                        help_text="Original URL of the job if it was web scraped.",
                        max_length=2000,
                        null=True,
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times the job listing has been viewed.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date when the job listing was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date when the job listing was last updated.",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="The category this job belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="categories.category",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="The company offering this job.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="companies.company",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        help_text="The geographical location of the job.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="categories.location",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who posted this job listing.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posted_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Job",
                "verbose_name_plural": "Jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "resume_file",
                    models.FileField(
                        blank=True,
                        help_text="Applicant's resume for this specific application. (e.g., stored in S3/Cloud Storage)",
                        null=True,
                        upload_to="application_resumes/",
                    ),
                ),
                (
                    "cover_letter_text",
                    models.TextField(
                        blank=True,
                        help_text="Applicant's cover letter for this specific application.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("reviewed", "Reviewed"),
                            ("interview", "Interview Scheduled"),
                            ("offer", "Offer Extended"),
                            ("hired", "Hired"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="pending",
                        help_text="Current status of the job application.",
                        max_length=20,
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the application was submitted.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the application status was last updated.",
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        help_text="The user who submitted this application.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        help_text="The job to which this application pertains.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Application",
                "verbose_name_plural": "Job Applications",
                "ordering": ["-applied_at"],
                "unique_together": {("job", "applicant")},
            },
        ),
    ]
