# Generated by Django 5.1.1 on 2025-08-09 07:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("job_applied", "Job Applied"),
                            ("application_status_update", "Application Status Update"),
                            ("new_job_posting", "New Job Posting"),
                            ("company_review", "Company Review"),
                            ("message_received", "Message Received"),
                            ("payment_confirmation", "Payment Confirmation"),
                            ("system_alert", "System Alert"),
                        ],
                        default="system_alert",
                        help_text="Type of notification.",
                        max_length=50,
                    ),
                ),
                (
                    "object_id",
                    models.UUIDField(
                        help_text="The UUID of the object this notification refers to."
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="The content of the notification message."
                    ),
                ),
                (
                    "read",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the notification has been read by the recipient.",
                    ),
                ),
                (
                    "emailed",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if an email notification has been sent.",
                    ),
                ),
                (
                    "in_app",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates if the notification is visible in-app.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the notification was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the notification was last updated.",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who initiated the action (optional).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiated_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="The content type of the object this notification refers to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        help_text="The user who receives the notification.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
