# Generated by Django 5.1.1 on 2025-08-09 07:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Full name of the company.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description of the company."
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        help_text="Official company website URL.",
                        max_length=2000,
                        null=True,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Company logo. (e.g., stored in S3/Cloud Storage)",
                        null=True,
                        upload_to="company_logos/",
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True,
                        help_text="Industry the company operates in.",
                        max_length=100,
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        help_text="Company size (e.g., '1-10', '11-50', '51-200', '201-500', '501-1000', '1000+').",
                        max_length=50,
                    ),
                ),
                (
                    "headquarters",
                    models.CharField(
                        blank=True,
                        help_text="Main office location of the company.",
                        max_length=255,
                    ),
                ),
                (
                    "founded_year",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Year the company was founded.", null=True
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the company profile has been verified.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date when the company profile was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date when the company profile was last updated.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CompanyMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("hiring_manager", "Hiring Manager"),
                            ("recruiter", "Recruiter"),
                        ],
                        default="recruiter",
                        help_text="Role of the user within the company.",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates if the membership is currently active.",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date when the user joined the company.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date when the membership was last updated.",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="The company this user is a member of.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="companies.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user associated with the company.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Member",
                "verbose_name_plural": "Company Members",
                "ordering": ["company__name", "user__email"],
                "unique_together": {("user", "company")},
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1 - Poor"),
                            (2, "2 - Fair"),
                            (3, "3 - Good"),
                            (4, "4 - Very Good"),
                            (5, "5 - Excellent"),
                        ],
                        help_text="Rating given to the company (1-5 stars).",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, help_text="Optional text comment for the review."
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the review has been approved by an admin.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date when the review was created."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date when the review was last updated.",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="The company being reviewed.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="companies.company",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who left the review.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="company_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Review",
                "verbose_name_plural": "Company Reviews",
                "ordering": ["-created_at"],
                "unique_together": {("company", "reviewer")},
            },
        ),
    ]
